project:
  type: website

website:
  title: "Data Dashboard Training Materials"
  navbar:
    left:
      - href: index.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto

