project:
  type: website
  resources:
    - lesson-materials/part-1/french-slides.pdf
    - lesson-materials/part-1/english.pdf
    - data-outputs.zip
    - images/

website:
  title: "Data Dashboard Training Materials"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Materials
        menu:
          - href: english-slides.qmd
            text: Part 1 Slides (EN)
          - href: french-slides.qmd
            text: Part 1 Slides (FR)
          - href: dashboarding-slides.qmd
            text: Part 2 Slides
          - href: dashboard-workshop-materials.qmd
            text: Part 2 Worksheet
          - href: hand-out.qmd
            text: Part 2 Reference sheet
  page-footer:
    center: "Ammnet Senegal 2025 Workshop | PATH "

format:
  html:
    page-layout: full
    theme: minty
    css: styles.css
    toc: true
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 200px
      gutter-width: 1.5rem

editor: visual

execute:
  freeze: auto