---
title: "Development of a dynamic dashboard for visualizing malaria epidemiological surveillance data with R-Shiny"
---

Website for the materials for the Ammnet Session - "*Development of a dynamic dashboard for visualizing malaria epidemiological surveillance data with R-Shiny*"


::: callout-important
To view the website in French - Open in Google Chrome - right click anywhere on the page and select "Translate to francias"

Pour afficher le site Web en français - Ouvrez dans Google Chrome - faites un clic droit n'importe où sur la page et sélectionnez "*Traduire en français*"
:::

**Date:** Friday 27th June

**Location:** Evasion 3 room

**Time:** 9am

# Description

Data visualization is a powerful tool for understanding and communicating data. This training session is a real practical guide that is addressed to professionals wishing to master the main steps of dynamic dashboard development for the visualization of malaria epidemiological surveillance data with R-Shiny from the DHIS2 platform. In this skills course, you will learn how to use the Pivot Table tool from the Data Visualize module of DHIS2 for manual data download. To prepare the data for visualization. Creating efficient and attractive visualizations by choosing the right chart type for data, properly adjusting axes for truth and accuracy, building parameters through visual choices. To deploy a Shiny application for your dynamic dashboards. This will give you the keys to successfully creating a dynamic dashboard for data visualization.

Before starting the training session, it is important to master the basics in descriptive data analysis, install R and the RStudio IDE, and install the required packages for the training.


Installation Guide: 
👉 <a href="lesson-materials/installation-guide.pdf" download>Download Install guide (EN) </a> 

👉 <a href="lesson-materials/installation-guide-FR.pdf" download>Download Install guide (FR) </a> 


```{r eval = FALSE}
# Packages installation ==========================================================================
install.packages("janitor")   #"janitor has simple little tools for examining and cleaning dirty data."
install.packages("shiny")     #"shiny: core package to build apps."
install.packages("bslib")     #"theming (Bootstrap customization) and modern dashboard design elements."
install.packages("tidyverse") #"Data wrangling (dplyr, ggplot2, readr…)."
install.packages("DT")        #"DT: interactive tables."
install.packages("plotly")    #"plotly: interactive plots."
install.packages("leaflet")   #"leaflet: mapping spatial data."
install.packages("sf")        #"sf: mapping spatial data."
install.packages("lubridate") #"lubridate for dealting with date-time."
install.packages("bsicons")   #"bsicons: Bootstrap icons for Shiny apps."
install.packages("scales")    #"scales: for formatting numbers, dates, and other data types in a consistent way."

# Packages load ===================================================================================
library(janitor)
library(shiny)
library(bslib)
library(tidyverse)
library(DT)
library(plotly)
library(leaflet)
library(sf)
library(lubridate)
library(bsicons)
library(scales)

```

# Objectives

## Part 1

-   Learn how to access DHIS2

-   Explore some existing dashboards to see graphical functionality

-   Learn how to make a data query to access the data elements, time period and geographical units of interest

-   Download data as a csv

-   Read data into R

-   Clean data, including name cleaning, visual inspection of outliers/missing data, cross-referencing different variables

The outcome of this session is a cleaned malaria dataset that we’ll use for part 2

## Part 2

-   Understand key elements of Shiny Dashbaords

-   Gain hands on experience customising Shiny Dashboards

-   Create your own Shiny Dashbaord

The outcome of this session is a fully interactive local App displaying key malaria program metrics.

# Materials

+-------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Part 1 Slides           | [**English**](english-slides.qmd)                                                                                                                                                        |
|                         |                                                                                                                                                                                          |
|                         | [**French**](french-slides.qmd)                                                                                                                                                          |
+-------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Part 2 - Data downloads | Download the following files and save them to your R project in a folder called: `data-outputs`. If you didn't complete Part 1 don't worry the final dataset is included in this folder! |
|                         |                                                                                                                                                                                          |
|                         | 👉 <a href="data-outputs.zip" download>Download data-outputs.zip</a>                                                                                                                     |
+-------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Part 2 - Slides         | Click [here](dashboarding-slides.qmd)                                                                                                                                                    |
+-------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Part 2 - Worksheet      | Click [here](dashboard-workshop-materials.qmd)                                                                                                                                           |
+-------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+